version: "3.8"

services:
  backend:
    restart: always
    depends_on:
      - postgres
    build:
      context: .
      target: backend
    env_file:
        - .env
    command: "uvicorn main:app --host 0.0.0.0 --port 8000 --log-level info --log-config logging.conf"
    ports:
    - 8000:8000
    networks:
      backend:


  postgres:
    restart: always
    image: postgres:13-alpine
    container_name: postgres
    ports:
      - 5434:5432
    env_file:
        - .env
    volumes:
      - ./postgres/postgres:/var/lib/postgresql/data/
    networks:
      backend:


volumes:
  postgres_data:

networks:
  backend: